INSERT INTO HOTEL_ROOM (ROOM_ID,ROOM_NAME,HOTEL_ID,CAPACITY,PRICE,ROOM_NUM)
		VALUES ('dd','aa','dd',5,50,'aa');	
        
UPDATE HOTEL_LIST 
SET HOTEL_NAME='dd', ADDR_SD='ad', ADDR_SGG='asdf', ADDR_EMD='asdf', TOTAL_ROOM=#{total_room} LON=#{lon}, LAT=#{lat}, AMENITIES=#{amenities}, GRADE=#{grade}, HOTEL_IMG=#{hotel_img} 
WHERE HOTEL_ID=1001;

SELECT * FROM HOTEL_ROOM ORDER BY ROOM_NUM;
		SELECT * FROM USERS ;

SELECT * 
FROM HOTEL_RESERVE
WHERE TO_DATE(START_DATE, 'yyyy mm dd') > TO_DATE(SYSDATE, 'yyyy mm dd');

SELECT TO_DATE(SYSDATE, 'yyyy mm dd') AS "현재시간"  FROM DUAL;

--오늘 숙박 중인 예약 건  
SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE(SYSDATE, 'yyyy mm dd') 
BETWEEN TO_DATE(START_DATE, 'yyyy mm dd') 
AND TO_DATE(END_DATE, 'yyyy mm dd');

-- 이건 되네..
SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE('2020-09-07') BETWEEN TO_DATE(START_DATE) AND TO_DATE(END_DATE);

-- RESERVE + HOTEL + ROOM + USERS
SELECT *
FROM HOTEL_RESERVE RSV
JOIN USERS U ON(RSV.USER_EMAIL = U.EMAIL)
JOIN HOTEL_LIST H ON(RSV.HOTEL_ID = H.HOTEL_ID)
JOIN HOTEL_ROOM RM ON(RSV.ROOM_ID = RM.ROOM_ID)
WHERE TO_DATE(RSV.START_DATE) >= TO_DATE(SYSDATE);
WHERE RSV.RSV_ID='rv0003';

-- ㅅㄷㄴㅅ
SELECT *
FROM HOTEL_RESERVE RSV
JOIN USERS U ON(RSV.USER_EMAIL = U.EMAIL)
JOIN HOTEL_LIST H ON(RSV.HOTEL_ID = H.HOTEL_ID)
JOIN HOTEL_ROOM RM ON(RSV.ROOM_ID = RM.ROOM_ID)
WHERE TO_DATE(START_DATE) >= TO_DATE(SYSDATE) AND 
H.HOTEL_NAME LIKE '%%' AND
U.NAME LIKE '%어피치%';



--어드민 rsv 업데이트
UPDATE HOTEL_RESERVE R
SET R.HOTEL_ID=(SELECT H.HOTEL_ID FROM HOTEL_LIST H WHERE H.HOTEL_NAME='센터마크호텔'),
R.USER_EMAIL=(SELECT U.EMAIL FROM USERS U WHERE U.NAME='어피치'),
R.ROOM_ID=(SELECT RM.ROOM_ID FROM HOTEL_ROOM RM WHERE RM.ROOM_NAME='스위트' AND 
                                                    RM.HOTEL_ID=(SELECT H2.HOTEL_ID FROM HOTEL_LIST H2 WHERE H2.HOTEL_NAME='센터마크호텔')),
R.START_DATE=TO_DATE(SYSDATE),
R.END_DATE=TO_DATE(SYSDATE),
R.PAY_YN='N'
WHERE R.RSV_ID='rv0001';

UPDATE HOTEL_RESERVE SET HOTEL_ID='ht0001', ROOM_ID='rm0003', USER_EMAIL='ryan@gmail.com',
START_DATE=TO_DATE('2020-09-07') WHERE RSV_ID='rv0001' ;

SELECT *
FROM HOTEL_RESERVE
WHERE RSV_ID='rv0001';

SELECT COUNT(*) FROM HOTEL_RESERVE
		WHERE TO_DATE(SYSDATE) BETWEEN TO_DATE(START_DATE) AND TO_DATE(END_DATE);

SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE(START_DATE) = TO_DATE('20200901');

-- 기간 검색
SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE(START_DATE) >= TO_DATE(TO_CHAR('2020-09-06')) AND 
    TO_DATE(END_DATE) <= TO_DATE(TO_CHAR('2020-09-12'));

SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE(START_DATE) >= TO_DATE('2020-09-06') AND 
    TO_DATE(END_DATE) <= TO_DATE('2020-09-12');

SELECT * FROM HOTEL_RESERVE
WHERE TO_DATE(START_DATE) = TO_DATE('2020-09-06', 'YYYY-MM-DD');

SELECT TO_DATE('2020-09-07', 'yyyy mm dd'), TO_DATE(SYSDATE, 'yyyy mm dd') A FROM DUAL;

INSERT INTO HOTEL_RESERVE VALUES ('rv1010','hy101','rm101','aaa@aaa.com',
		TO_DATE('2020-02-20', 'yyyy mm dd'),TO_DATE('2020-03-31', 'yyyy mm dd'),SYSDATE,'Y');

SELECT *
FROM HOTEL_ROOM
order by room_id desc
