CREATE TABLE GAME_USER(
    ID VARCHAR2(10),
    PWD VARCHAR2(20),
    NAME VARCHAR2(30)
);
ALTER TABLE GAME_USER ADD CONSTRAINT USER_PK PRIMARY KEY (ID);
ALTER TABLE GAME_USER ADD CONSTRAINT USER_PWD_NN CHECK (PWD IS NOT NULL);
ALTER TABLE GAME_USER ADD CONSTRAINT USER_PWD_CH CHECK (LENGTH(PWD)>3);
ALTER TABLE GAME_USER ADD CONSTRAINT USER_NAME_NN CHECK (NAME IS NOT NULL);



CREATE SEQUENCE ITEM_SEQ START WITH 100 INCREMENT BY 1;
SELECT ITEM_SEQ.CURRVAL FROM DUAL; 

CREATE TABLE GAME_ITEM(
    ID NUMBER(10),
    NAME VARCHAR2(30),
    PRICE NUMBER(20)
);
ALTER TABLE GAME_ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY (ID);
ALTER TABLE GAME_ITEM ADD CONSTRAINT ITEM_UN UNIQUE (NAME);
ALTER TABLE GAME_ITEM ADD REGDATE DATE;
COMMIT;

INSERT INTO GAME_USER VALUES('id01','pw01','LEE');
INSERT INTO GAME_USER VALUES('id02','pw02','KIM');
INSERT INTO GAME_USER VALUES('id03','pw03','HWANG');
COMMIT;

INSERT INTO GAME_ITEM VALUES(ITEM_SEQ.NEXTVAL, 'KNIFE', 10000, SYSDATE);
INSERT INTO GAME_ITEM VALUES(ITEM_SEQ.NEXTVAL, 'GUN', 20000, SYSDATE);
INSERT INTO GAME_ITEM VALUES(ITEM_SEQ.NEXTVAL, 'CAR', 30000, SYSDATE);
COMMIT;

CREATE SEQUENCE USER_ITEM_SEQ START WITH 1000 INCREMENT BY 1;
SELECT USER_ITEM_SEQ.CURRVAL FROM DUAL; 
CREATE TABLE USER_ITEM(
    ID VARCHAR2(20),
    USER_ID VARCHAR2(10),
    ITEM_ID NUMBER(10),
    QT NUMBER(10)
);

ALTER TABLE USER_ITEM ADD CONSTRAINT UI_PK PRIMARY KEY (ID);
ALTER TABLE USER_ITEM ADD CONSTRAINT UI_FK1 FOREIGN KEY (USER_ID) REFERENCES GAME_USER(ID);
ALTER TABLE USER_ITEM MODIFY QT DEFAULT 1;

-- 202008031000
INSERT INTO USER_ITEM VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD') || USER_ITEM_SEQ .NEXTVAL, 'id01', 100, 3);
INSERT INTO USER_ITEM VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD') || USER_ITEM_SEQ .NEXTVAL, 'id01', 101, 1);

-- 제약조건땜에 안됨
DELETE FROM GAME_USER WHERE ID='id01';

-- 제약조건 비활성화
ALTER TABLE USER_ITEM DISABLE CONSTRAINT UI_PK;
ALTER TABLE USER_ITEM DISABLE CONSTRAINT UI_FK1;

-- 실행됨
DELETE FROM GAME_USER WHERE ID='id01';
ROLLBACK; 

-- 다시 활성화
ALTER TABLE USER_ITEM ENABLE CONSTRAINT UI_PK;
ALTER TABLE USER_ITEM ENABLE CONSTRAINT UI_FK1;


/*
DROP SEQUENCE USER_ITEM_SEQ0;
DROP SEQUENCE USER_ITEM_SEQ;
DROP SEQUENCE USERITEM_SEQ;
DROP SEQUENCE ITEM_SEQ0;
DROP SEQUENCE ITEM_SEQ;

DROP TABLE USER_ITEM;
DROP TABLE GAME_USER;
DROP TABLE GAME_ITEM;
*/

