/*
DDL
CREATE, ALTER DROP(TRUNCATE)

ALTER
 - COLMN 변경
 - CONSTRAINT
 
 SEQUENCE
*/


INSERT INTO USERS VALUES ('id37', 'pwd33', '말자');
INSERT INTO USERS VALUES ('id38', 'pwd33', '말자');

ROLLBACK;
COMMIT;

DROP TABLE CUSTOMER;
DESC PRODUCT;
CREATE TABLE CUSTOMER(
    ID NUMBER(5),
    PWD VARCHAR2(20),
    NAME VARCHAR2(20)
);

-- CC:  제약조건의 이름 / UNIQUE :  중복되지 않는 값
ALTER TABLE CUSTOMER ADD CONSTRAINT CC CHECK (PWD IS NOT NULL);
ALTER TABLE CUSTOMER ADD CONSTRAINT UU UNIQUE (PWD, NAME);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK PRIMARY KEY (ID);
ALTER TABLE CUSTOMER DROP CONSTRAINT CC;

INSERT INTO CUSTOMER VALUES ('id01', null , 'james');
INSERT INTO CUSTOMER VALUES ('id01', 'pwd1' , 'james');


ALTER TABLE CUSTOM ADD GRADE NUMBER(10);
ALTER TABLE CUSTOM RENAME COLUMN GRADE TO LEVELS;
ALTER TABLE CUSTOMER MODIFY LEVELS NUMBER(5);
ALTER TABLE CUSTOM DROP COLUMN LEVELS;


----------------------
DESC CORDER;
SELECT * FROM  CORDER;
CREATE TABLE CORDER(
    ID NUMBER(10),
    USERID VARCHAR2(20),
    PRODUCTID NUMBER(5)
);

ALTER TABLE CORDER ADD CONSTRAINT OP PRIMARY KEY (ID);
ALTER TABLE CORDER ADD CONSTRAINT ORDER_FK1
    FOREIGN KEY(USERID) REFERENCES CUSTOMER(ID);
ALTER TABLE CORDER ADD CONSTRAINT ORDER_FK2
    FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(ID); 
ALTER TABLE CORDER DROP CONSTRAINT ORDER_FK2;

INSERT INTO CORDER VALUES(1, 'ID9999', '3333'); 

--시퀀스: 발급기
CREATE SEQUENCE PRODUCT_SEQ START WITH 100 INCREMENT BY 1;
SELECT PRODUCT_SEQ.CURRVAL FROM DUAL; --현재카운트 조회

TRUNCATE TABLE PRODUCT; --데이터만 삭제
DELETE FROM PRODUCT; --연결된 데이터도 그냥 삭제?

INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'바지1',10000,3.5,SYSDATE);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'바지2',20000,3.5,SYSDATE);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'바지3',30000,3.5,SYSDATE);
COMMIT;




