SELECT COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL) FROM EMP WHERE DEPTNO = 10;
SELECT * FROM EMP;
SELECT SUM(DISTINCT SAL), SUM(SAL) FROM EMP;

SELECT COUNT(*)
FROM EMP
WHERE COMM IS NOT NULL;

SELECT TO_CHAR(HIREDATE, 'YYYY'), AVG(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY');

-- SLA의 평균이 3000이상인 그룹만 출력
-- 단 SAL 2000이상 직원대상
SELECT  DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE SAL >= 2000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL)>=3000
ORDER BY 1;

SELECT * FROM EMP ORDER BY JOB;

SELECT TO_CHAR(HIREDATE, 'YYYY') AS YEAR, JOB, TO_CHAR(ROUND(AVG(SAL*12+NVL(COMM,0)),1), '$999,999,999') AS AVG_SAL
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), JOB
ORDER BY YEAR, JOB;

-- 입사연도 > 업종별로 구분하여 평균연봉을 구하시오


SELECT JOB
FROM EMP
GROUP BY JOB
HAVING MAX(SAL)