--ADAMS가 속한 부서 직원의 평균 월급
SELECT AVG(SAL)
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='ADAMS')
GROUP BY DEPTNO;

--ADAMS가 속한 부서 직원의 평균 월급보다 많이 받는 직원
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP
                        WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='ADAMS')
                        GROUP BY DEPTNO);

-- NEW YORK에 근무하는 직원들의 월급 평균보다 많이 받는 직원들을 조회하시오
SELECT AVG(SAL)
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL > (SELECT AVG(SAL)
    FROM EMP
    WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK'));

--ALLEN 의 입사월에 들어온 직원 조회
SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE, 'YY/MM') = 
    (SELECT TO_CHAR(HIREDATE, 'YY/MM')
    FROM EMP
    WHERE ENAME = 'ALLEN');
    
--SCOTT과 JAMES가 속한 부서의 직원
SELECT * FROM EMP
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE ENAME IN ('SCOTT', 'JAMES'));

--WHERE에서 비교할 인자 서로 맞춰야함
SELECT * FROM EMP
WHERE (DEPTNO, SAL) IN (
    SELECT DEPTNO, AVG(SAL) FROM EMP 
    GROUP BY DEPTNO);
    
    
SELECT E.ENAME, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
--위아래 연산결과 같음
SELECT ENAME, GRADE
FROM 
    (SELECT E.ENAME, S.GRADE FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL);


-- p262 Q1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D ON(E.DEPTNO=D.DEPTNO)
WHERE JOB = (SELECT JOB FROM EMP
WHERE ENAME='ALLEN');

--Q2
SELECT E.EMPNO, E.ENAME, D.DNAME, TO_CHAR(E.HIREDATE,'YYYY-MM-DD') AS HIREDATE, E.SAL, S.GRADE
FROM EMP E 
    JOIN DEPT D ON(E.DEPTNO=D.DEPTNO)
    JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND HISAL)
WHERE E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO ASC;

--Q3
SELECT D10.EMPNO, D10.ENAME, D10.DEPTNO, D.DNAME, D.LOC
FROM 
    (SELECT * FROM EMP WHERE DEPTNO=10) D10
    JOIN DEPT D ON (D10.DEPTNO = D.DEPTNO)
WHERE D10.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO=30);

--Q4 다중행함수 사용(MAX)
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E
    JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')
ORDER BY EMPNO;

--Q4 다중행함수 사용 X
SELECT  E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E
    JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
WHERE SAL > ALL(SELECT SAL FROM EMP WHERE JOB='SALESMAN')
ORDER BY EMPNO;

