SELECT ENAME, SAL+12+COMM FROM EMP;
SELECT ENAME, SAL+12+NVL(COMM,0) FROM EMP;
SELECT ENAME, SAL+12+NVL(COMM,0) AS "TOTAL SAL" FROM EMP;
SELECT ENAME || JOB AS "NAME+JOB" FROM EMP;

SELECT JOB, SAL FROM EMP ORDER BY JOB,SAL DESC;
SELECT * FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, NVL(COMM,0) AS COMM 
FROM EMP 
ORDER BY HIREDATE,COMM DESC;

SELECT EMPNO, ENAME, (SAL*12+(NVL(COMM,0)))*96.7 AS ANNSAL 
FROM EMP;

