SELECT * FROM EMP WHERE JOB='SALESMAN'
AND COMM>0
AND HIREDATE > TO_DATE('1981/02','YYYY/MM')
AND HIREDATE < TO_DATE('1981/03','YYYY/MM')
ORDER BY HIREDATE;

SELECT * FROM EMP WHERE JOB='SALESMAN'
AND COMM>0
AND TO_CHAR(HIREDATE, 'YY/MM') = '81/02'
ORDER BY HIREDATE;

SELECT * FROM EMP 
WHERE SAL>3000 OR HIREDATE > TO_DATE('1981/04','YYYY/MM');

SELECT * FROM EMP
WHERE SAL*12>1800 AND HIREDATE < TO_DATE('1981/05', 'YYYY/MM');

SELECT * FROM EMP
WHERE SAL IN (3000, 1100, 1600);

SELECT * FROM EMP
WHERE SAL NOT IN (3000, 1100, 1600);

SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME LIKE '%S';

SELECT * FROM EMP 
WHERE ENAME LIKE 'A\_A%' ESCAPE '\'; 

SELECT ENAME, SAL FROM EMP WHERE SAL < 1000
UNION
SELECT ENAME, SAL FROM EMP WHERE SAL > 3000;

SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10, 20)
INTERSECT
SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10);

-- 1
SELECT * FROM EMP WHERE ENAME LIKE '%S';

-- 2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO 
FROM EMP 
WHERE DEPTNO=30 AND JOB='SALESMAN';

-- 3-1
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO 
FROM EMP 
WHERE DEPTNO IN (20, 30) AND SAL>2000;
 
-- 3-2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO IN (20, 30)
INTERSECT 
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SAL>2000;

-----------------

SELECT LOWER(ENAME), SAL FROM EMP;
SELECT NAME, LENGTH(NAME) FROM USERS;

SELECT LENGTH('한글'), LENGTHB('한') FROM DUAL;
SELECT * FROM USERS;

INSERT INTO USERS VALUES ('id58', 'pwd58', '구름');
INSERT INTO USERS VALUES ('id05', 'pwss', '이말자님');

 SELECT '010-1234-5959' AS YGTPNB, REPLACE('010-1234-5959', '-', '') AS ONEE, REPLACE('010-1234-5959', '-') AS ONE FROM DUAL;

SELECT RPAD('970128-1155151', 14, '*') FROM EMP;

SELECT SUBSTR('970128-1155151', 1, 7) FROM EMP;
SELECT RPAD(SUBSTR('970128-1155151', 1, 7), 14, '*') FROM EMP;

SELECT INSTR('970128-1155151', '-', '1') FROM EMP;

SELECT ENAME, SYSDATE, HIREDATE, TRUNC(SYSDATE - HIREDATE) AS "WORKING DAYS",
TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12) AS "WORKING YEARS"
FROM EMP;

SELECT ENAME, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12) AS "WORKING YEARS"
FROM EMP
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12)>=38;

SELECT * FROM EMP 
WHERE HIREDATE > TO_DATE('1981/01','YYYY/MM')
AND HIREDATE < TO_DATE('1981/10','YYYY/MM')
ORDER BY HIREDATE;

SELECT * FROM EMP 
WHERE HIREDATE BETWEEN  TO_DATE('1981/02','YYYY/MM') AND TO_DATE('1981/10','YYYY/MM')
ORDER BY HIREDATE;

SELECT ENAME, TO_CHAR(HIREDATE, 'YYYY/MM/DD : HH.MM.SS') AS DDD FROM EMP;
SELECT ENAME, HIREDATE AS DDD FROM EMP;

-- 연 기준으로 반올림
SELECT ROUND(SYSDATE, 'YYYY') FROM DUAL;

SELECT TRIM(TO_CHAR(SAL, 'L999,999,999')) AS DD FROM EMP;

-- NVL2 : NULL이면, NULL아니면
SELECT ENAME, NVL(COMM, 0), NVL2(COMM, 'N', 'Y') AS "Y/N", COMM,
NVL2(COMM, SAL+COMM * 12, SAL*12)
FROM EMP; 

SELECT ENAME, JOB,
CASE JOB
    WHEN 'MANAGER' THEN SAL*1.1
    WHEN 'ANALYST' THEN SAL*2.2 -- WHEN JOB=='ANALYST' 랑똑같음  CASE옆에 JOB이 있어서 생략됨
    ELSE SAL*0.9
END AS BONUS
,SAL
FROM EMP;

SELECT ENAME, JOB,
CASE
    WHEN SAL > 4000 THEN '상'
    WHEN SAL >= 3000 THEN '중'
    ELSE '하'
END AS GRADE
,SAL
FROM EMP;


-----------------------------

SELECT * FROM ITEMS;
ALTER TABLE ITEMS ADD REGDATE DATE;

INSERT INTO ITEMS VALUES('it88', '바지', 100, TO_DATE('20200730', 'YYYY/MM/DD'));
