SELECT * FROM GAME_USER;
SELECT * FROM GAME_ITEM;
DESC GAME_ITEM;

INSERT INTO GAME_ITEM VALUES(1000,cup,8000,SYSDATE);


SELECT U.ID, U.USER_ID, U.ITEM_ID, U.QT, G.NAME AS ITEM_NAME
FROM USER_ITEM U, GAME_ITEM G
WHERE U.ITEM_ID = G.ID;